
services:
  prompts:
    image: manologcode/prompts
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prompts
    environment:
      - LLM_URL=http://192.168.1.69:11434/api/generate
    ports:
      - 5001:5088
    volumes:
      - ./app:/app

